# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       isomd5sum

# >> macros
# << macros
%define keepstatic 1

Summary:    Utilities for working with md5sum implanted in ISO images
Version:    1.0.12
Release:    1
Group:      Applications/System
License:    GPLv2+
URL:        http://git.fedorahosted.org/git/?p=isomd5sum.git;a=summary
Source0:    %{name}-%{version}.tar.xz
Source100:  isomd5sum.yaml
BuildRequires:  pkgconfig(popt)
BuildRequires:  pkgconfig(python2)

%description
The isomd5sum package contains utilities for implanting and verifying
an md5sum implanted into an ISO9660 image.


%package devel
Summary:    Development headers and library for using isomd5sum
Group:      Development/System
Requires:   %{name} = %{version}-%{release}
Provides:   %{name}-static = %{version}-%{release}

%description devel
This contains header files and a library for working with the isomd5sum
implanting and checking.


%package -n python-isomd5sum
Summary:    Python bindings for isomd5sum
Group:      Development/System
Requires:   %{name} = %{version}-%{release}

%description -n python-isomd5sum
Python bindings for isomd5sum.


%prep
%setup -q -n %{name}-%{version}/upstream

# >> setup
sed -i 's,LIBDIR = lib64,LIBDIR = lib,g' Makefile
# << setup

%build
# >> build pre
CFLAGS="$RPM_OPT_FLAGS -Wno-strict-aliasing"; export CFLAGS
make checkisomd5 implantisomd5 pyisomd5sum.so
# << build pre



# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
make DESTDIR=$RPM_BUILD_ROOT install-bin install-devel install-python
# << install pre

# >> install post
# << install post

%files
%defattr(-,root,root,-)
%doc COPYING
%{_bindir}/implantisomd5
%{_bindir}/checkisomd5
%{_mandir}/man*/*
# >> files
# << files

%files devel
%defattr(-,root,root,-)
%{_includedir}/*.h
%{_libdir}/*.a
# >> files devel
# << files devel

%files -n python-isomd5sum
%defattr(-,root,root,-)
%{python_sitearch}/pyisomd5sum.so
# >> files python-isomd5sum
# << files python-isomd5sum
